# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b83167f87c0e2d01b47fe27ad13f25c401b5e730868c5047c72427ee0ae58d0bd570b74d61cbced8a90cf0e1bcb6875f1dfe77822624043a93a4f184a1bdf9

test:
  secret_key_base: 854c06807519bdc1d4bef3d14efcf479ef905cac72cd57d54359731b3e29dd26b0de2adb20992be20afee4344494dbdb6609fcd024d6bda14995960ae63200d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
